spring.application.name=conectapro
server.servlet.context-path=/api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
