import type { Teacher } from '@/types/teacher'

export const SUBJECT_OPTIONS = ['Matemática', 'Inglês', 'Física', 'Química', 'Programação']

export const MIN_PRICE_PER_HOUR = 40
export const MAX_PRICE_PER_HOUR = 120

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: 'ana-lima',
    name: 'Ana Lima',
    initials: 'AL',
    subjects: ['Matemática', 'Física', 'Cálculo'],
    rating: 4.9,
    reviewCount: 128,
    modalities: ['online', 'presencial'],
    pricePerHour: 60,
    verified: true,
    bio: `Olá! Sou professora de Matemática e Física com mais de 8 anos de experiência no ensino particular. Formada pela USP em Licenciatura em Matemática e com mestrado em Física Aplicada, já ajudei mais de 200 alunos a superarem suas dificuldades e conquistarem suas metas — do Ensino Médio até a graduação.\n\nMeu método é baseado em exemplos práticos e resolução guiada de problemas. Acredito que cada aluno aprende de forma diferente, por isso adapto as aulas ao seu ritmo e estilo de aprendizado. As aulas são dinâmicas, com exercícios comentados e material de apoio personalizado enviado após cada sessão.`,
    availability: ['Manhã (8h – 12h)', 'Noite (19h – 22h)'],
    weekDays: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex'],
  },
  {
    id: 'bruno-alves',
    name: 'Bruno Alves',
    initials: 'BA',
    subjects: ['Inglês', 'Espanhol', 'Conversação'],
    rating: 4.8,
    reviewCount: 94,
    modalities: ['online'],
    pricePerHour: 55,
    verified: true,
    bio: `Sou professor de idiomas com fluência em Inglês e Espanhol, certificado pelo Cambridge (C2 Proficiency) e pelo DELE Avançado. Trabalho com alunos de todos os níveis — do básico absoluto à preparação para exames internacionais como IELTS, TOEFL e DELE.\n\nMinhas aulas são 100% conversacionais e contextualizadas. Acredito que o segredo de aprender um idioma é usá-lo desde o primeiro dia. Trago materiais autênticos — séries, podcasts, artigos — para tornar o aprendizado relevante e divertido.`,
    availability: ['Tarde (14h – 18h)', 'Noite (19h – 22h)'],
    weekDays: ['Ter', 'Qua', 'Qui', 'Sáb'],
  },
  {
    id: 'carla-souza',
    name: 'Carla Souza',
    initials: 'CS',
    subjects: ['Química', 'Biologia'],
    rating: 4.7,
    reviewCount: 61,
    modalities: ['presencial'],
    pricePerHour: 70,
    verified: false,
  },
  {
    id: 'diego-martins',
    name: 'Diego Martins',
    initials: 'DM',
    subjects: ['Matemática', 'Programação', 'Lógica'],
    rating: 4.6,
    reviewCount: 45,
    modalities: ['online'],
    pricePerHour: 45,
    verified: true,
    bio: `Desenvolvedor de software e professor apaixonado por lógica e resolução de problemas. Formado em Ciência da Computação pela UNICAMP, atuo como engenheiro de software há 6 anos e ensino programação e matemática nas horas vagas.\n\nEspecialidade: transformar assuntos "difíceis" em algo intuitivo. Trabalho muito com visualizações, analogias e projetos práticos. Ótimo para quem está ingressando na área de tecnologia ou precisa reforçar a base matemática para concursos e vestibulares.`,
    availability: ['Manhã (8h – 12h)', 'Tarde (14h – 17h)'],
    weekDays: ['Seg', 'Qua', 'Sex'],
  },
  {
    id: 'fernanda-costa',
    name: 'Fernanda Costa',
    initials: 'FC',
    subjects: ['Física', 'Química'],
    rating: 4.5,
    reviewCount: 32,
    modalities: ['presencial'],
    pricePerHour: 80,
    verified: false,
  },
  {
    id: 'gabriel-rocha',
    name: 'Gabriel Rocha',
    initials: 'GR',
    subjects: ['Programação'],
    rating: 5,
    reviewCount: 210,
    modalities: ['online'],
    pricePerHour: 90,
    verified: true,
  },
  {
    id: 'helena-dias',
    name: 'Helena Dias',
    initials: 'HD',
    subjects: ['Inglês', 'Redação'],
    rating: 3.3,
    reviewCount: 18,
    modalities: ['online', 'presencial'],
    pricePerHour: 40,
    verified: false,
    bio: `Professora de Inglês com foco em leitura, escrita e gramática aplicada. Formada em Letras pela PUC-SP, atendo principalmente estudantes do Ensino Médio e adultos que retomam o idioma após anos sem praticar.\n\nMinhas aulas são pacientes e estruturadas. Gosto de começar do diagnóstico: entender onde o aluno tem dificuldade e construir um plano personalizado a partir daí. Atendo online e presencial na zona sul de São Paulo.`,
    availability: ['Noite (19h – 22h)'],
    weekDays: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
  },
  {
    id: 'igor-santos',
    name: 'Igor Santos',
    initials: 'IS',
    subjects: ['Matemática'],
    rating: 4.8,
    reviewCount: 76,
    modalities: ['presencial'],
    pricePerHour: 65,
    verified: true,
  },
  {
    id: 'juliana-prado',
    name: 'Juliana Prado',
    initials: 'JP',
    subjects: ['Química'],
    rating: 4.9,
    reviewCount: 140,
    modalities: ['online'],
    pricePerHour: 120,
    verified: true,
  },
]
