import type { Teacher } from '@/types/teacher'

export const SUBJECT_OPTIONS = ['Matemática', 'Inglês', 'Física', 'Química', 'Programação']

export const MIN_PRICE_PER_HOUR = 40
export const MAX_PRICE_PER_HOUR = 120

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: 'ana-lima',
    name: 'Ana Lima',
    initials: 'AL',
    subjects: ['Matemática', 'Física'],
    rating: 4.9,
    reviewCount: 128,
    modalities: ['online', 'presencial'],
    pricePerHour: 60,
    verified: true,
  },
  {
    id: 'bruno-alves',
    name: 'Bruno Alves',
    initials: 'BA',
    subjects: ['Inglês', 'Espanhol'],
    rating: 4.8,
    reviewCount: 94,
    modalities: ['online'],
    pricePerHour: 55,
    verified: true,
  },
  {
    id: 'carla-souza',
    name: 'Carla Souza',
    initials: 'CS',
    subjects: ['Química', 'Biologia'],
    rating: 4.7,
    reviewCount: 61,
    modalities: ['presencial'],
    pricePerHour: 70,
    verified: false,
  },
  {
    id: 'diego-martins',
    name: 'Diego Martins',
    initials: 'DM',
    subjects: ['Matemática', 'Programação'],
    rating: 4.6,
    reviewCount: 45,
    modalities: ['online'],
    pricePerHour: 45,
    verified: true,
  },
  {
    id: 'fernanda-costa',
    name: 'Fernanda Costa',
    initials: 'FC',
    subjects: ['Física', 'Química'],
    rating: 4.5,
    reviewCount: 32,
    modalities: ['presencial'],
    pricePerHour: 80,
    verified: false,
  },
  {
    id: 'gabriel-rocha',
    name: 'Gabriel Rocha',
    initials: 'GR',
    subjects: ['Programação'],
    rating: 5,
    reviewCount: 210,
    modalities: ['online'],
    pricePerHour: 90,
    verified: true,
  },
  {
    id: 'helena-dias',
    name: 'Helena Dias',
    initials: 'HD',
    subjects: ['Inglês'],
    rating: 3.3,
    reviewCount: 18,
    modalities: ['online', 'presencial'],
    pricePerHour: 40,
    verified: false,
  },
  {
    id: 'igor-santos',
    name: 'Igor Santos',
    initials: 'IS',
    subjects: ['Matemática'],
    rating: 4.8,
    reviewCount: 76,
    modalities: ['presencial'],
    pricePerHour: 65,
    verified: true,
  },
  {
    id: 'juliana-prado',
    name: 'Juliana Prado',
    initials: 'JP',
    subjects: ['Química'],
    rating: 4.9,
    reviewCount: 140,
    modalities: ['online'],
    pricePerHour: 120,
    verified: true,
  },
]
